/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    darkMode: "class",
    theme: {
        extend: {
            fontFamily: {
                sans: ["Montserrat", "sans-serif"],
            },
            colors: {
                primary: {
                    DEFAULT: "#605D55",
                    50: "#EFEFEE",
                    100: "#CECDCA",
                    200: "#B6B4B1",
                    300: "#94928D",
                    400: "#807D77",
                    500: "#605D55",
                    600: "#57554D",
                    700: "#44423C",
                    800: "#35332F",
                    900: "#282724",
                },
                secondary: {
                    DEFAULT: "#bb9348",
                    50: "#f8f4ed",
                    100: "#e6dec6",
                    200: "#e0cdab",
                    300: "#d1b784",
                    400: "#c9a96d",
                    500: "#bb9348",
                    600: "#aa8642",
                    700: "#856833",
                    800: "#675128",
                    900: "#4f321e",
                },
                gray: {
                    DEFAULT: "#fdfdfd",
                    defaultSubtle: "#f4f4f4",
                    disabled: "#232533",
                    borderDefault: "#d1d1d1",
                    borderDisabled: "#eeeeee",
                    textTitle: "#353535",
                    textBody: "#7b7b7b",
                    textSubtitle: "#4e4e4e",
                    textCaption: "#c2c2c2",
                    textNegative: "#fdfdfd",
                    textDisabled: "#a4a4a4",
                },
                textColor: "#353535",
                grayTextBody: "#7B7B7B",
                grayTextIcon: "#C2C2C2",
                graySurface: "#F4F4F4",
                borderColor: "#ebebeb",
            },
        },
    },
    plugins: [],
};
